"""Add Phase 5 NLP tables and columns

Revision ID: 146892327439
Revises: 
Create Date: 2025-10-27 15:27:39.261399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '146892327439'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_snapshots',
    sa.Column('snapshot_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_feeds', sa.Integer(), nullable=False),
    sa.Column('active_feeds', sa.Integer(), nullable=False),
    sa.Column('validation_success_rate', sa.Float(), nullable=False),
    sa.Column('avg_response_time', sa.Float(), nullable=False),
    sa.Column('trending_topics', sa.JSON(), nullable=True),
    sa.Column('health_distribution', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_date')
    )
    op.create_table('email_digests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('schedule_type', sa.Enum('DAILY', 'WEEKLY', 'CUSTOM', name='scheduletype'), nullable=False),
    sa.Column('schedule_cron', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('next_send_at', sa.DateTime(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('open_count', sa.Integer(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_digests_next_send_at'), 'email_digests', ['next_send_at'], unique=False)
    op.create_index(op.f('ix_email_digests_user_id'), 'email_digests', ['user_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('canonical_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('aliases', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entity_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('frequency_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_canonical_name'), 'entities', ['canonical_name'], unique=True)
    op.create_index(op.f('ix_entities_frequency_count'), 'entities', ['frequency_count'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('NEW_ARTICLE', 'TRENDING_TOPIC', 'FEED_UPDATED', 'SYSTEM_ALERT', name='notificationtype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('action_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('saved_searches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('search_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_searches_user_id'), 'saved_searches', ['user_id'], unique=False)
    op.create_table('search_queries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('query_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('search_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filters_applied', sa.JSON(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('clicked_results', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_queries_timestamp'), 'search_queries', ['timestamp'], unique=False)
    op.create_index(op.f('ix_search_queries_user_id'), 'search_queries', ['user_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feed', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sa.Enum('BLOG', 'NEWSLETTER', 'PODCAST', 'JOURNAL', 'PREPRINT', 'ORGANIZATION', 'AGGREGATOR', 'VIDEO', 'DOCS', 'FORUM', 'DATASET', 'CODE_REPO', 'NEWSROOM', 'EDUCATION', 'REDDIT', 'MEDIUM', 'YOUTUBE', 'GITHUB', 'SUBSTACK', 'DEVTO', 'HACKERNEWS', 'TWITTER', 'ARXIV', name='sourcetype'), nullable=True),
    sa.Column('mediums', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('topic_weights', sa.JSON(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('format', sa.Enum('RSS', 'ATOM', 'JSONFEED', 'UNKNOWN', name='feedformat'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('last_validated', sa.DateTime(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('contributor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('popularity_score', sa.Float(), nullable=False),
    sa.Column('validation_count', sa.Integer(), nullable=False),
    sa.Column('curation_status', sa.Enum('VERIFIED', 'UNVERIFIED', 'ARCHIVED', 'EXPERIMENTAL', 'INACTIVE', name='curationstatus'), nullable=True),
    sa.Column('curation_since', sa.DateTime(), nullable=True),
    sa.Column('curation_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('curation_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provenance_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provenance_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provenance_license', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('discover_enabled', sa.Boolean(), nullable=False),
    sa.Column('discover_config', sa.JSON(), nullable=True),
    sa.Column('relations', sa.JSON(), nullable=True),
    sa.Column('mappings', sa.JSON(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_popularity_score'), 'sources', ['popularity_score'], unique=False)
    op.create_table('subtopics',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_topic', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtopics_approved'), 'subtopics', ['approved'], unique=False)
    op.create_index(op.f('ix_subtopics_article_count'), 'subtopics', ['article_count'], unique=False)
    op.create_index(op.f('ix_subtopics_parent_topic'), 'subtopics', ['parent_topic'], unique=False)
    op.create_table('topic_evolution_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('source_topic', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('target_topics', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_evolution_events_detected_at'), 'topic_evolution_events', ['detected_at'], unique=False)
    op.create_table('topic_sentiment_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('avg_sentiment', sa.Float(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=False),
    sa.Column('neutral_count', sa.Integer(), nullable=False),
    sa.Column('negative_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_sentiment_daily_topic'), 'topic_sentiment_daily', ['topic'], unique=False)
    op.create_table('topic_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feed_count', sa.Integer(), nullable=False),
    sa.Column('validation_frequency', sa.Float(), nullable=False),
    sa.Column('avg_health_score', sa.Float(), nullable=False),
    sa.Column('snapshot_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_stats_snapshot_date'), 'topic_stats', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_topic_stats_topic'), 'topic_stats', ['topic'], unique=False)
    op.create_table('topics',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('related_topics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trending_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('baseline_mean', sa.Float(), nullable=False),
    sa.Column('baseline_std', sa.Float(), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('representative_articles', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trending_topics_period_start'), 'trending_topics', ['period_start'], unique=False)
    op.create_index(op.f('ix_trending_topics_topic_id'), 'trending_topics', ['topic_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('followed_feeds', sa.JSON(), nullable=True),
    sa.Column('preferred_topics', sa.JSON(), nullable=True),
    sa.Column('blocked_topics', sa.JSON(), nullable=True),
    sa.Column('interaction_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('analytics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feed_source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('period_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('new_items', sa.Integer(), nullable=False),
    sa.Column('updated_items', sa.Integer(), nullable=False),
    sa.Column('deleted_items', sa.Integer(), nullable=False),
    sa.Column('update_count', sa.Integer(), nullable=False),
    sa.Column('avg_update_interval_hours', sa.Float(), nullable=True),
    sa.Column('min_update_interval_hours', sa.Float(), nullable=True),
    sa.Column('max_update_interval_hours', sa.Float(), nullable=True),
    sa.Column('avg_content_length', sa.Float(), nullable=True),
    sa.Column('avg_title_length', sa.Float(), nullable=True),
    sa.Column('has_images_count', sa.Integer(), nullable=False),
    sa.Column('has_video_count', sa.Integer(), nullable=False),
    sa.Column('has_audio_count', sa.Integer(), nullable=False),
    sa.Column('avg_links_per_item', sa.Float(), nullable=True),
    sa.Column('avg_categories_per_item', sa.Float(), nullable=True),
    sa.Column('unique_authors', sa.Integer(), nullable=False),
    sa.Column('items_with_full_content', sa.Integer(), nullable=False),
    sa.Column('items_with_summary_only', sa.Integer(), nullable=False),
    sa.Column('items_with_media', sa.Integer(), nullable=False),
    sa.Column('fetch_attempts', sa.Integer(), nullable=False),
    sa.Column('fetch_successes', sa.Integer(), nullable=False),
    sa.Column('fetch_failures', sa.Integer(), nullable=False),
    sa.Column('uptime_percentage', sa.Float(), nullable=True),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=True),
    sa.Column('min_response_time_ms', sa.Float(), nullable=True),
    sa.Column('max_response_time_ms', sa.Float(), nullable=True),
    sa.Column('topic_distribution', sa.JSON(), nullable=True),
    sa.Column('keyword_frequency', sa.JSON(), nullable=True),
    sa.Column('extra_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_feed_source_id'), 'analytics', ['feed_source_id'], unique=False)
    op.create_table('collaborative_matrix',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feed_id_1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feed_id_2', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('co_occurrence_score', sa.Float(), nullable=False),
    sa.Column('support', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id_1'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['feed_id_2'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaborative_matrix_feed_id_1'), 'collaborative_matrix', ['feed_id_1'], unique=False)
    op.create_index(op.f('ix_collaborative_matrix_feed_id_2'), 'collaborative_matrix', ['feed_id_2'], unique=False)
    op.create_table('enrichment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feed_source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enriched_at', sa.DateTime(), nullable=False),
    sa.Column('enrichment_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enricher', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('discovered_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('discovered_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('discovered_language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('discovered_author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detected_format', sa.Enum('RSS', 'ATOM', 'JSONFEED', 'UNKNOWN', name='feedformat'), nullable=True),
    sa.Column('detected_platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('platform_metadata', sa.JSON(), nullable=True),
    sa.Column('icon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('favicon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('banner_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('freshness_score', sa.Float(), nullable=True),
    sa.Column('entry_count', sa.Integer(), nullable=True),
    sa.Column('has_full_content', sa.Boolean(), nullable=False),
    sa.Column('avg_content_length', sa.Float(), nullable=True),
    sa.Column('content_types', sa.JSON(), nullable=True),
    sa.Column('content_samples', sa.JSON(), nullable=True),
    sa.Column('estimated_frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('update_regularity', sa.Float(), nullable=True),
    sa.Column('update_intervals', sa.JSON(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('availability_score', sa.Float(), nullable=True),
    sa.Column('uptime_percentage', sa.Float(), nullable=True),
    sa.Column('suggested_topics', sa.JSON(), nullable=True),
    sa.Column('topic_confidence', sa.JSON(), nullable=True),
    sa.Column('auto_keywords', sa.JSON(), nullable=True),
    sa.Column('has_itunes', sa.Boolean(), nullable=False),
    sa.Column('has_media_rss', sa.Boolean(), nullable=False),
    sa.Column('has_dublin_core', sa.Boolean(), nullable=False),
    sa.Column('has_geo', sa.Boolean(), nullable=False),
    sa.Column('extension_data', sa.JSON(), nullable=True),
    sa.Column('seo_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seo_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('og_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('twitter_card', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('social_metadata', sa.JSON(), nullable=True),
    sa.Column('encoding', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generator', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('cloud', sa.JSON(), nullable=True),
    sa.Column('internal_links', sa.Integer(), nullable=True),
    sa.Column('external_links', sa.Integer(), nullable=True),
    sa.Column('broken_links', sa.Integer(), nullable=True),
    sa.Column('redirect_chains', sa.JSON(), nullable=True),
    sa.Column('uses_https', sa.Boolean(), nullable=False),
    sa.Column('has_valid_ssl', sa.Boolean(), nullable=False),
    sa.Column('security_headers', sa.JSON(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrichment_feed_source_id'), 'enrichment', ['feed_source_id'], unique=True)
    op.create_table('feed_embeddings',
    sa.Column('feed_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('feed_id')
    )
    op.create_table('feed_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('content_html', sa.JSON(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('quality_processed', sa.Boolean(), nullable=False),
    sa.Column('entities_processed', sa.Boolean(), nullable=False),
    sa.Column('sentiment_processed', sa.Boolean(), nullable=False),
    sa.Column('topics_processed', sa.Boolean(), nullable=False),
    sa.Column('quality_processed_at', sa.DateTime(), nullable=True),
    sa.Column('entities_processed_at', sa.DateTime(), nullable=True),
    sa.Column('sentiment_processed_at', sa.DateTime(), nullable=True),
    sa.Column('nlp_failures', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_entries_feed_id'), 'feed_entries', ['feed_id'], unique=False)
    op.create_index(op.f('ix_feed_entries_guid'), 'feed_entries', ['guid'], unique=True)
    op.create_index(op.f('ix_feed_entries_pub_date'), 'feed_entries', ['pub_date'], unique=False)
    op.create_table('feed_poll_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILURE', name='pollstatus'), nullable=False),
    sa.Column('error_message', sa.JSON(), nullable=True),
    sa.Column('articles_discovered', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_poll_jobs_feed_id'), 'feed_poll_jobs', ['feed_id'], unique=False)
    op.create_index(op.f('ix_feed_poll_jobs_status'), 'feed_poll_jobs', ['status'], unique=False)
    op.create_table('fetch_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feed_source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('fetch_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('etag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_modified', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('items_found', sa.Integer(), nullable=True),
    sa.Column('items_new', sa.Integer(), nullable=True),
    sa.Column('items_updated', sa.Integer(), nullable=True),
    sa.Column('fetch_duration_ms', sa.Integer(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['feed_source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fetch_logs_feed_source_id'), 'fetch_logs', ['feed_source_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feed_source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('guid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('enclosures', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_index(op.f('ix_items_feed_source_id'), 'items', ['feed_source_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feed_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delivery_method', sa.Enum('WEBSOCKET', 'EMAIL', 'IN_APP', name='deliverymethod'), nullable=False),
    sa.Column('frequency', sa.Enum('INSTANT', 'HOURLY', 'DAILY', 'WEEKLY', 'OFF', name='notificationfrequency'), nullable=False),
    sa.Column('quiet_hours_start', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quiet_hours_end', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_table('recommendation_interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feed_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_interactions_feed_id'), 'recommendation_interactions', ['feed_id'], unique=False)
    op.create_index(op.f('ix_recommendation_interactions_timestamp'), 'recommendation_interactions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_recommendation_interactions_user_id'), 'recommendation_interactions', ['user_id'], unique=False)
    op.create_table('user_feed_follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feed_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('followed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_feed_follows_feed_id'), 'user_feed_follows', ['feed_id'], unique=False)
    op.create_index(op.f('ix_user_feed_follows_user_id'), 'user_feed_follows', ['user_id'], unique=False)
    op.create_table('validations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feed_source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('validated_at', sa.DateTime(), nullable=False),
    sa.Column('validator_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('schema_valid', sa.Boolean(), nullable=False),
    sa.Column('schema_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('schema_errors', sa.JSON(), nullable=True),
    sa.Column('is_accessible', sa.Boolean(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('redirect_count', sa.Integer(), nullable=True),
    sa.Column('final_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_items', sa.Boolean(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('has_required_fields', sa.Boolean(), nullable=False),
    sa.Column('missing_fields', sa.JSON(), nullable=True),
    sa.Column('format_valid', sa.Boolean(), nullable=False),
    sa.Column('format_errors', sa.JSON(), nullable=True),
    sa.Column('xml_well_formed', sa.Boolean(), nullable=False),
    sa.Column('links_checked', sa.Integer(), nullable=True),
    sa.Column('links_valid', sa.Integer(), nullable=True),
    sa.Column('links_broken', sa.Integer(), nullable=True),
    sa.Column('broken_link_urls', sa.JSON(), nullable=True),
    sa.Column('images_checked', sa.Integer(), nullable=True),
    sa.Column('images_accessible', sa.Integer(), nullable=True),
    sa.Column('image_errors', sa.JSON(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('compression_ratio', sa.Float(), nullable=True),
    sa.Column('https_enabled', sa.Boolean(), nullable=False),
    sa.Column('ssl_valid', sa.Boolean(), nullable=False),
    sa.Column('security_issues', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('validation_report', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validations_feed_source_id'), 'validations', ['feed_source_id'], unique=False)
    op.create_table('article_quality_scores',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('depth_score', sa.Integer(), nullable=True),
    sa.Column('reference_score', sa.Integer(), nullable=True),
    sa.Column('author_score', sa.Integer(), nullable=True),
    sa.Column('domain_score', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['feed_entries.id'], ),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_index(op.f('ix_article_quality_scores_computed_at'), 'article_quality_scores', ['computed_at'], unique=False)
    op.create_table('article_sentiment',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('classification', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['feed_entries.id'], ),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_index(op.f('ix_article_sentiment_computed_at'), 'article_sentiment', ['computed_at'], unique=False)
    op.create_table('entity_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_method', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('context', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mentioned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['feed_entries.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_mentions_article_id'), 'entity_mentions', ['article_id'], unique=False)
    op.create_index(op.f('ix_entity_mentions_entity_id'), 'entity_mentions', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_mentions_entity_id'), table_name='entity_mentions')
    op.drop_index(op.f('ix_entity_mentions_article_id'), table_name='entity_mentions')
    op.drop_table('entity_mentions')
    op.drop_index(op.f('ix_article_sentiment_computed_at'), table_name='article_sentiment')
    op.drop_table('article_sentiment')
    op.drop_index(op.f('ix_article_quality_scores_computed_at'), table_name='article_quality_scores')
    op.drop_table('article_quality_scores')
    op.drop_index(op.f('ix_validations_feed_source_id'), table_name='validations')
    op.drop_table('validations')
    op.drop_index(op.f('ix_user_feed_follows_user_id'), table_name='user_feed_follows')
    op.drop_index(op.f('ix_user_feed_follows_feed_id'), table_name='user_feed_follows')
    op.drop_table('user_feed_follows')
    op.drop_index(op.f('ix_recommendation_interactions_user_id'), table_name='recommendation_interactions')
    op.drop_index(op.f('ix_recommendation_interactions_timestamp'), table_name='recommendation_interactions')
    op.drop_index(op.f('ix_recommendation_interactions_feed_id'), table_name='recommendation_interactions')
    op.drop_table('recommendation_interactions')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_items_feed_source_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_fetch_logs_feed_source_id'), table_name='fetch_logs')
    op.drop_table('fetch_logs')
    op.drop_index(op.f('ix_feed_poll_jobs_status'), table_name='feed_poll_jobs')
    op.drop_index(op.f('ix_feed_poll_jobs_feed_id'), table_name='feed_poll_jobs')
    op.drop_table('feed_poll_jobs')
    op.drop_index(op.f('ix_feed_entries_pub_date'), table_name='feed_entries')
    op.drop_index(op.f('ix_feed_entries_guid'), table_name='feed_entries')
    op.drop_index(op.f('ix_feed_entries_feed_id'), table_name='feed_entries')
    op.drop_table('feed_entries')
    op.drop_table('feed_embeddings')
    op.drop_index(op.f('ix_enrichment_feed_source_id'), table_name='enrichment')
    op.drop_table('enrichment')
    op.drop_index(op.f('ix_collaborative_matrix_feed_id_2'), table_name='collaborative_matrix')
    op.drop_index(op.f('ix_collaborative_matrix_feed_id_1'), table_name='collaborative_matrix')
    op.drop_table('collaborative_matrix')
    op.drop_index(op.f('ix_analytics_feed_source_id'), table_name='analytics')
    op.drop_table('analytics')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_trending_topics_topic_id'), table_name='trending_topics')
    op.drop_index(op.f('ix_trending_topics_period_start'), table_name='trending_topics')
    op.drop_table('trending_topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_topic_stats_topic'), table_name='topic_stats')
    op.drop_index(op.f('ix_topic_stats_snapshot_date'), table_name='topic_stats')
    op.drop_table('topic_stats')
    op.drop_index(op.f('ix_topic_sentiment_daily_topic'), table_name='topic_sentiment_daily')
    op.drop_table('topic_sentiment_daily')
    op.drop_index(op.f('ix_topic_evolution_events_detected_at'), table_name='topic_evolution_events')
    op.drop_table('topic_evolution_events')
    op.drop_index(op.f('ix_subtopics_parent_topic'), table_name='subtopics')
    op.drop_index(op.f('ix_subtopics_article_count'), table_name='subtopics')
    op.drop_index(op.f('ix_subtopics_approved'), table_name='subtopics')
    op.drop_table('subtopics')
    op.drop_index(op.f('ix_sources_popularity_score'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_search_queries_user_id'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_timestamp'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_saved_searches_user_id'), table_name='saved_searches')
    op.drop_table('saved_searches')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_entities_frequency_count'), table_name='entities')
    op.drop_index(op.f('ix_entities_canonical_name'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_email_digests_user_id'), table_name='email_digests')
    op.drop_index(op.f('ix_email_digests_next_send_at'), table_name='email_digests')
    op.drop_table('email_digests')
    op.drop_table('analytics_snapshots')
    # ### end Alembic commands ###
