/**
 * Feed data loading utilities
 * Reads feed data from JSON files generated by Python backend
 */

import { readFileSync } from 'fs';
import { join } from 'path';
import { parse } from 'yaml';

export interface FeedSource {
  id?: string;
  url: string;
  title: string;
  source_type?: string;
  description?: string;
  website_url?: string;
  verified?: boolean;
  is_active?: boolean;
  topics?: string[];
  tags?: string[];
  language?: string;
  author?: string;
  created_at?: string;
  updated_at?: string;
}

export interface FeedsData {
  sources: FeedSource[];
  metadata?: {
    total_count: number;
    last_updated: string;
    version: string;
  };
}

/**
 * Load feeds from JSON/YAML files
 * Tries multiple sources in order: feeds.json, feeds.enriched.yaml, feeds.yaml
 */
export async function loadFeeds(): Promise<FeedsData> {
  const dataDir = join(process.cwd(), '../../data');
  
  // Try JSON first (fastest to parse)
  try {
    const jsonPath    = join(dataDir, 'feeds.json');
    const jsonContent = readFileSync(jsonPath, 'utf-8');
    const data        = JSON.parse(jsonContent);
    
    return {
      sources: data.sources || data.feeds || (Array.isArray(data) ? data : []),
      metadata: data.metadata,
    };
  } catch (e) {
    // JSON not available, try YAML
  }
  
  // Try enriched YAML
  try {
    const yamlPath    = join(dataDir, 'feeds.enriched.yaml');
    const yamlContent = readFileSync(yamlPath, 'utf-8');
    const data        = parse(yamlContent);
    
    return {
      sources: data.sources || data.feeds || (Array.isArray(data) ? data : []),
      metadata: data.metadata,
    };
  } catch (e) {
    // Enriched YAML not available, try regular YAML
  }
  
  // Fallback to feeds.yaml
  try {
    const yamlPath    = join(dataDir, 'feeds.yaml');
    const yamlContent = readFileSync(yamlPath, 'utf-8');
    const data        = parse(yamlContent);
    
    return {
      sources: data.sources || data.feeds || (Array.isArray(data) ? data : []),
      metadata: data.metadata,
    };
  } catch (e) {
    throw new Error('Failed to load feeds data from any source');
  }
}

/**
 * Filter feeds by source type
 */
export function filterBySourceType(
  feeds: FeedSource[],
  sourceType: string | null
): FeedSource[] {
  if (!sourceType) return feeds;
  return feeds.filter((feed) => feed.source_type === sourceType);
}

/**
 * Filter feeds by topic
 */
export function filterByTopic(
  feeds: FeedSource[],
  topic: string | null
): FeedSource[] {
  if (!topic) return feeds;
  return feeds.filter((feed) => feed.topics?.includes(topic));
}

/**
 * Filter feeds by verification status
 */
export function filterByVerified(
  feeds: FeedSource[],
  verified: boolean | null
): FeedSource[] {
  if (verified === null) return feeds;
  return feeds.filter((feed) => feed.verified === verified);
}

/**
 * Get unique source types from feed list
 */
export function getSourceTypes(feeds: FeedSource[]): string[] {
  const types = new Set<string>();
  
  for (const feed of feeds) {
    if (feed.source_type) {
      types.add(feed.source_type);
    }
  }
  
  return Array.from(types).sort();
}

/**
 * Get unique topics from feed list
 */
export function getTopics(feeds: FeedSource[]): string[] {
  const topics = new Set<string>();
  
  for (const feed of feeds) {
    if (feed.topics) {
      for (const topic of feed.topics) {
        topics.add(topic);
      }
    }
  }
  
  return Array.from(topics).sort();
}

/**
 * Get feed statistics
 */
export function getFeedStats(feeds: FeedSource[]) {
  return {
    total: feeds.length,
    verified: feeds.filter((f) => f.verified).length,
    active: feeds.filter((f) => f.is_active !== false).length,
    byType: getSourceTypes(feeds).reduce(
      (acc, type) => {
        acc[type] = feeds.filter((f) => f.source_type === type).length;
        return acc;
      },
      {} as Record<string, number>
    ),
    topicCount: getTopics(feeds).length,
  };
}

