/**
 * Feed data loading utilities
 * Reads feed data from JSON files generated by Python backend
 */

import { readFileSync } from "fs";
import { join } from "path";
import { parse } from "yaml";

import { getSourceTypes, getTopics, type FeedSource, type FeedsData } from "@/lib/feeds-filters";

export type { FeedSource, FeedsData };

export {
  filterBySourceType,
  filterByTopic,
  filterByVerified,
  getSourceTypes,
  getTopics,
} from "@/lib/feeds-filters";

function stableFeedId(feed: FeedSource, index: number): string {
  if (feed.id?.trim()) {
    return feed.id.trim();
  }

  const title = feed.title?.trim().toLowerCase();
  if (title) {
    return title.replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  }

  return `feed-${index + 1}`;
}

function normalizeFeedRecord(feed: FeedSource, index: number): FeedSource {
  return {
    ...feed,
    id: stableFeedId(feed, index),
    topics: feed.topics ?? feed.tags ?? [],
    tags: feed.tags ?? feed.topics ?? [],
  };
}

function hasExplicitBooleanValue<Key extends "verified" | "is_active">(
  feeds: FeedSource[],
  key: Key,
): boolean {
  return feeds.some((feed) => typeof feed[key] === "boolean");
}

function normalizeFeedsData(data: unknown): FeedsData {
  const container = data as {
    sources?: FeedSource[];
    feeds?: FeedSource[];
    metadata?: FeedsData["metadata"];
  };
  const sourceRecords = container?.sources || container?.feeds || (Array.isArray(data) ? data : []);

  return {
    sources: sourceRecords.map(normalizeFeedRecord),
    metadata: container?.metadata,
  };
}

function getDataDirectory(): string {
  return join(process.cwd(), "../../data");
}

export function loadFeedCatalog(): FeedsData {
  const dataDir = getDataDirectory();

  try {
    const jsonPath = join(dataDir, "feeds.enriched.json");
    const jsonContent = readFileSync(jsonPath, "utf-8");
    return normalizeFeedsData(JSON.parse(jsonContent));
  } catch {
    // Fall through to YAML sources.
  }

  try {
    const yamlPath = join(dataDir, "feeds.enriched.yaml");
    const yamlContent = readFileSync(yamlPath, "utf-8");
    return normalizeFeedsData(parse(yamlContent));
  } catch {
    // Fall through to the baseline catalog exports.
  }

  try {
    const jsonPath = join(dataDir, "feeds.json");
    const jsonContent = readFileSync(jsonPath, "utf-8");
    return normalizeFeedsData(JSON.parse(jsonContent));
  } catch {
    // Fall through to the authored baseline catalog.
  }

  try {
    const yamlPath = join(dataDir, "feeds.yaml");
    const yamlContent = readFileSync(yamlPath, "utf-8");
    return normalizeFeedsData(parse(yamlContent));
  } catch {
    throw new Error("Failed to load feeds data from any source");
  }
}

/**
 * Load feeds from JSON/YAML files
 * Tries multiple sources in order: feeds.enriched.json, feeds.enriched.yaml, feeds.json, feeds.yaml
 */
export async function loadFeeds(): Promise<FeedsData> {
  return loadFeedCatalog();
}

/**
 * Get feed statistics
 */
export function getFeedStats(feeds: FeedSource[]) {
  const sourceTypes = getSourceTypes(feeds);
  const hasVerificationMetadata = hasExplicitBooleanValue(feeds, "verified");
  const hasActivityMetadata = hasExplicitBooleanValue(feeds, "is_active");

  return {
    total: feeds.length,
    verified: feeds.filter((feed) => feed.verified === true).length,
    active: feeds.filter((feed) => feed.is_active === true).length,
    hasVerificationMetadata,
    hasActivityMetadata,
    sourceTypeCount: sourceTypes.length,
    byType: sourceTypes.reduce(
      (acc, type) => {
        acc[type] = feeds.filter((f) => f.source_type === type).length;
        return acc;
      },
      {} as Record<string, number>,
    ),
    topicCount: getTopics(feeds).length,
  };
}
