-- =====================================================================
-- Historical reference only.
-- =====================================================================
--
-- The canonical runtime schema now lives in Alembic revisions under
-- packages/alembic/versions and is applied via
-- ai_web_feeds.storage.DatabaseManager.create_db_and_tables().
--
-- This placeholder intentionally contains no executable SQL so legacy Phase 5
-- references fail safe instead of reintroducing stale schema drift.
